# Generated by Django 2.0.9 on 2019-04-01 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindBikeFriends_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_status',
        ),
    ]
