# Generated by Django 2.0.9 on 2019-04-01 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FindBikeFriends_core', '0002_remove_user_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Etkinlik Tipi',
                'verbose_name_plural': 'Etkinlik Tipleri',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Gelen Kullanıcılar'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='tag',
        ),
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='FindBikeFriends_core.EventTag', verbose_name='Etkinlik Tagi'),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FindBikeFriends_core.EventType', verbose_name='Etkinlik Tipi'),
        ),
    ]
