# Generated by Django 2.0.9 on 2019-04-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindBikeFriends_core', '0003_auto_20190401_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='FindBikeFriends_core.EventTag', verbose_name='Etkinlik Tagları'),
        ),
    ]
