# Generated by Django 2.0.9 on 2019-04-01 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FindBikeFriends_core', '0004_auto_20190401_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementimage',
            name='advertisement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FindBikeFriends_core.Advertisement', verbose_name='Reklamveren'),
        ),
        migrations.AlterField(
            model_name='advertisementimage',
            name='image',
            field=models.ImageField(upload_to='images/advertisement/', verbose_name='Reklam Resimi'),
        ),
        migrations.AlterField(
            model_name='followers',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to=settings.AUTH_USER_MODEL, verbose_name='Takip Edilen'),
        ),
        migrations.AlterField(
            model_name='followers',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to=settings.AUTH_USER_MODEL, verbose_name='Takip Eden'),
        ),
    ]
