# Generated by Django 2.0.9 on 2019-04-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindBikeFriends_core', '0005_auto_20190401_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='tag',
        ),
        migrations.AddField(
            model_name='eventtype',
            name='type',
            field=models.TextField(default=0, verbose_name='Tag'),
            preserve_default=False,
        ),
    ]
