# Generated by Django 2.0.9 on 2019-04-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindBikeFriends_core', '0006_auto_20190404_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtag',
            name='tag',
            field=models.TextField(verbose_name='Etkinlik Tag'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='type',
            field=models.TextField(verbose_name='Etkinlik Tip'),
        ),
    ]
