# Generated by Django 2.0.9 on 2019-04-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindBikeFriends_core', '0007_auto_20190404_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtag',
            name='tag',
            field=models.CharField(max_length=255, verbose_name='Etkinlik Tagi'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='type',
            field=models.CharField(max_length=255, verbose_name='Etkinlik Tipi'),
        ),
    ]
