# Generated by Django 2.0.9 on 2019-04-04 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindBikeFriends_core', '0008_auto_20190404_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
    ]
