# Generated by Django 2.0.9 on 2019-05-06 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FindBikeFriends_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Chat', 'verbose_name_plural': 'Chats'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Chat Message', 'verbose_name_plural': 'Chat Messages'},
        ),
        migrations.RemoveField(
            model_name='chat',
            name='first_messsage',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Chat Name'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_owner', to=settings.AUTH_USER_MODEL, verbose_name='Owner User'),
        ),
        migrations.RemoveField(
            model_name='chat',
            name='chat_sent_user',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_sent_user',
            field=models.ManyToManyField(related_name='sendusers', to=settings.AUTH_USER_MODEL, verbose_name='Sent User'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_chat', to='FindBikeFriends_app.Chat', verbose_name='Chat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat_message',
            field=models.CharField(max_length=500, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_user', to=settings.AUTH_USER_MODEL, verbose_name='Send User'),
        ),
    ]
