# Generated by Django 2.0.9 on 2019-05-06 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FindBikeFriends_app', '0002_auto_20190506_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Chat Name')),
                ('group_name_user', models.ManyToManyField(related_name='sendusers', to=settings.AUTH_USER_MODEL, verbose_name='Sent User')),
            ],
            options={
                'verbose_name': 'Bisiklet Grubu',
                'verbose_name_plural': 'Bisiklet Grupları',
            },
        ),
        migrations.RemoveField(
            model_name='chat',
            name='chat_sent_user',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='chat_title',
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_owner', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan kişi'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tarih'),
        ),
        migrations.AddField(
            model_name='chat',
            name='bike_group',
            field=models.ManyToManyField(related_name='bikegroup', to='FindBikeFriends_app.BikeGroup', verbose_name='Bisiklet Grubu'),
        ),
    ]
