# Generated by Django 2.0.9 on 2019-05-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindBikeFriends_app', '0003_auto_20190506_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyaddress',
            options={'ordering': ('-name',), 'verbose_name': 'Şirket Adresi', 'verbose_name_plural': 'Şirket Adresleri'},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktif'),
        ),
    ]
