# Generated by Django 2.0.9 on 2019-05-13 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindBikeFriends_app', '0004_auto_20190506_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikegroup',
            old_name='group_name_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='approved',
        ),
    ]
