# Generated by Django 2.0.9 on 2019-05-13 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FindBikeFriends_app', '0005_auto_20190513_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_owner', to=settings.AUTH_USER_MODEL, verbose_name='Reklamveren Firma'),
        ),
    ]
