# Generated by Django 2.0.9 on 2019-05-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindBikeFriends_app', '0006_auto_20190513_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(default=0, upload_to='images/event/', verbose_name='Reklam Thumbnail'),
            preserve_default=False,
        ),
    ]
